<?php
// $Id$: indextank.module

require_once(dirname(__FILE__) . '/indextank_client.php');

// Installation and configuration hooks

function indextank_help($path, $arg) {
  $output = '';
  switch ($path) {
    case "admin/help#indextank":
      $output = '<p><a href="http://www.indextank.com">IndexTank</a>'.  t("search engine in your website") .'</p>';
      break;
  }
  return $output;
} // function indextank_help


function indextank_admin() {
  $form = array();

  $form['#submit'] = array('indextank_admin_submit');

  $form['indextank_apiurl'] = array(
    '#type' => 'textfield',
    '#title' => t('Api Url'),
    '#default_value' => variable_get('indextank_apiurl', ''),
    '#size' => 60,
    '#maxlength' => 60,
    '#description' => t("Your IndexTank url api"),
    '#required' => TRUE,
  );

  $form['indextank_setup'] = array(
    '#type' => 'submit',
    '#value' => t('Index all your documents'),
    '#weight' => 1,
  );

  return system_settings_form($form);
}

function indextank_admin_validate($form, &$form_state) {
  $api_url = $form_state['values']['indextank_apiurl'];
  if (!indextank_valid_apiurl($api_url)) {
    form_set_error('indextank_apiurl', t('You must enter a valid IndexTank api url.'));
  }
}

function indextank_admin_submit($form, &$form_state) {

  $clicked_button = $form_state['clicked_button']['#id'];

  if ($clicked_button == 'edit-indextank-setup') {
    // Create new index
    $api_url = $form_state['values']['indextank_apiurl'];
    $index_name = 'drupal';

    $api = new ApiClient($api_url);
    $index = $api->get_index($index_name);

    if ($index->exists()) {
      $index->delete_index();
    }

    $index->create_index();

    while (! $index->has_started()) {
      sleep(1);
    }

    // Index created
    $query = db_query(
      "SELECT n.nid, n.type, n.title, n.created as timestamp, nr.body
      FROM {node} n
      INNER JOIN {node_revisions} nr ON n.nid = nr.nid
      WHERE n.status = 1;"
    );

    while ($row = db_fetch_object($query)) {
      indextank_index_document($index, $row);
    }
  }
}

function indextank_menu() {

  $items = array();

  $items['admin/settings/indextank'] = array(
    'title' => 'IndexTank settings',
    'description' => 'Config IndexTank search engine and index all your documents',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('indextank_admin'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
   );

  return $items;
}

function indextank_valid_apiurl($api_url) {
  return (bool) preg_match("
      /^http:\/\/:[[:alnum:][:punct:]]+@[a-z0-9]{4,8}\.api\.indextank\.com$/",
      $api_url);
}


function indextank_do_uninstall() {
  // Destroy drupal index
  $api_url = variable_get('indextank_apiurl', '');
  $index_name = 'drupal';

  $api = new ApiClient($api_url);
  $index = $api->get_index($index_name);

  if ($index->exists()) {
    $index->delete_index();
  }
  // Index destroyed
}


// Search and index hooks

function indextank_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  if ($op == 'insert' || $op == 'update') {
    $api_url = variable_get('indextank_apiurl', '');
    $index_name = 'drupal';

    $api = new ApiClient($api_url);
    $index = $api->get_index($index_name);

    indextank_index_document($index, $node);
  }
}

function indextank_search($op = 'search', $keys = null) {
  switch ($op) {
    case 'name':
      return t('IndexTank');
    case 'search':
      $api_url = variable_get('indextank_apiurl', '');
      $index_name = 'drupal';

      $api = new ApiClient($api_url);
      $index = $api->get_index($index_name);

      $indextank_search_result = $index->search($keys);

      $doc_ids = array();
      foreach ($indextank_search_result->results as $doc_result) {
        $doc_ids[] = $doc_result->docid;
      }
      $nodes = array();

      if (count($doc_ids) > 0) {
        $placeholders = db_placeholders($doc_ids);

        $query = db_query("SELECT n.*, u.name FROM {node} n inner join users u on n.uid = u.uid WHERE n.nid IN ($placeholders)", $doc_ids);
        while ($row = db_fetch_object($query)) {
          $node = array(
            'link' => url("node/{$row->nid}"),
            'type' => $row->type,
            'title' => $row->title,
            'user' => $row->name,
            'date' => $row->changed,
          );
          $nodes[] = $node;
        }
      }
      return $nodes;
  }
}

function indextank_index_document($index, $document) {
  $data = array(
    'text' => $document->title . ' ' . $document->body,
    'title' => $document->title,
    'content' => $document->body,
    'timestamp' => $document->timestamp,
    'match_all_field'=> 'all_items',
  );

  $docid = $document->nid;
  $index->add_document($docid, $data);
}

/**
 *********************
 * Alter drupal forms
 *********************
 */

/**
 * Implementation of hook_form_[form_id]_alter().
 */
function indextank_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'search_theme_form' || $form_id == 'search_block_form') {
    if (!isset($form['#submit'])) {
      $form['#submit'] = array('indextank_search_box_form_submit');
    }
    else {
      $key = array_search('search_box_form_submit', $form['#submit']);
      if ($key !== FALSE) {
        // Replace the search module's function.
        $form['#submit'][$key] = 'indextank_search_box_form_submit';
      }
    }
  }
}

/**
 * Process a block search form submission.
 *
 * @see search_box_form_submit()
 */
function indextank_search_box_form_submit($form, &$form_state) {
  // The search form relies on control of the redirect destination for its
  // functionality, so we override any static destination set in the request,
  // for example by drupal_access_denied() or drupal_not_found()
  // (see http://drupal.org/node/292565).
  if (isset($_REQUEST['destination'])) {
    unset($_REQUEST['destination']);
  }
  if (isset($_REQUEST['edit']['destination'])) {
    unset($_REQUEST['edit']['destination']);
  }

  $form_id = $form['form_id']['#value'];
  $keys = $form_state['values'][$form_id];
  // Handle Apache webserver clean URL quirks.
  if (variable_get('clean_url', '0')) {
    $keys = str_replace('+', '%2B', $keys);
  }
  $form_state['redirect'] = 'search/indextank/'. trim($keys);
}

