<?php
// $Id$: indextank.module

require_once(dirname(__FILE__) . '/indextank_client.php');
include_once(dirname(__FILE__) . '/indextank.theme.inc');

// Load css and js
function indextank_init() {

  drupal_add_css(drupal_get_path('module', 'indextank') . '/indextank.css');
  //drupal_add_css('http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.11/themes/south-street/jquery-ui.css', 'external');
  drupal_add_js('document.write(unescape("%3Clink type=\'text/css\' rel=\'stylesheet\' href=\'' . 
    'http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.11/themes/south-street/jquery-ui.css' .
    '\' media=\'all\'%3E "));', 'inline'
  );

  drupal_add_js(drupal_get_path('module', 'indextank') . '/dateFormat.js');
  $external_js = array(
    'https://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js',
    'https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.11/jquery-ui.min.js',
    'https://github.com/flaptor/indextank-jquery/raw/1.x/jquery.indextank.ize.js',
    'https://github.com/flaptor/indextank-jquery/raw/1.x/jquery.indextank.ajaxsearch.js',
    'https://github.com/flaptor/indextank-jquery/raw/1.x/jquery.indextank.renderer.js',
    'https://github.com/flaptor/indextank-jquery/raw/1.x/jquery.indextank.instantlinks.js'
  );

  foreach ($external_js as $js) {
    drupal_add_js('document.write(unescape("%3Cscript src=\'' . $js .
                   '\' type=\'text/javascript\'%3E%3C/script%3E"));', 'inline');
  }
  drupal_add_js(indextank_search_js(), 'inline');
}

function indextank_do_uninstall() {
  // Destroy drupal index
  $api_url = variable_get('indextank_apiurl', '');
  $index_name = 'drupal';
  if ($api_url != '') {
  
    $api = new ApiClient($api_url);
    $index = $api->get_index($index_name);

    if ($index->exists()) {
      $index->delete_index();
    }
    // Index destroyed
  }
}

// Indextank menu
function indextank_help($path, $arg) {
  $output = '';
  switch ($path) {
    case "admin/help#indextank":
      $output = '<p><a href="http://www.indextank.com">IndexTank</a>'.  t("search engine in your website") .'</p>';
      break;
  }
  return $output;
}

function indextank_menu() {

  $items = array();

  $items['admin/settings/indextank'] = array(
    'title' => 'IndexTank settings',
    'description' => 'Config IndexTank search engine and index all your documents',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('indextank_admin'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
   );

  return $items;
}

function indextank_admin() {
  $form = array();

  $form['#submit'] = array('indextank_admin_submit');

  $form['indextank_apiurl'] = array(
    '#type' => 'textfield',
    '#title' => t('Api Url'),
    '#default_value' => variable_get('indextank_apiurl', ''),
    '#size' => 60,
    '#maxlength' => 60,
    '#description' => t("Your IndexTank url api"),
    '#required' => TRUE,
  );

  $form['indextank_public_apiurl'] = array(
    '#type' => 'textfield',
    '#title' => t('Public Api Url'),
    '#default_value' => variable_get('indextank_public_apiurl', ''),
    '#size' => 60,
    '#maxlength' => 60,
    '#description' => t("Your IndexTank public url api"),
    '#required' => TRUE,
  );

  $form['indextank_setup'] = array(
    '#type' => 'submit',
    '#value' => t('Index all your documents'),
    '#weight' => 1,
  );

  return system_settings_form($form);
}

// Submit Indextank api keys
function indextank_admin_submit($form, &$form_state) {

  $clicked_button = $form_state['clicked_button']['#id'];

  if ($clicked_button == 'edit-indextank-setup') {
    // Create new index
    $api_url = $form_state['values']['indextank_apiurl'];
    $index_name = 'drupal';

    $api = new ApiClient($api_url);
    $index = $api->get_index($index_name);

    if ($index->exists()) {
      $index->delete_index();
    }

    $public_search = true;
    $index->create_index($public_search);

    while (! $index->has_started()) {
      sleep(1);
    }

    // Index created
    if (is_drupal_version_6()) {
      $rows = db_query(
      "SELECT n.nid, n.type, n.title, n.created as timestamp, r.body as body, u.name name
         FROM {node} n, {node_revisions} r, {users} u
        WHERE n.nid = r.nid
          AND n.uid = u.uid
          AND n.status = 1;");
      $results = array();
      while ($row = db_fetch_object($rows)) {
        $results[] = $row;
      } 
    } else {
      $results = db_query(
      "SELECT n.nid, n.type, n.title, n.created as timestamp, fd.body_value as body, u.name name
         FROM node n, field_data_body fd, users u
        WHERE n.nid = fd.entity_id
          AND n.uid = u.uid
          AND n.status = 1;", array()
      );
    }

    $docs = array();
    foreach ($results as $row) {
      $fields = indextank_get_fields($row);
      $doc = array('docid' => $row->nid, 'fields' => $fields);
      $docs[] = $doc;

      if (count($docs) % 100 == 0) {
        $index->add_documents($docs);
        $docs = array();
      }
    }
    
    if (count($docs) > 0) {
        $out = $index->add_documents($docs);
    }
  }
}


// Index and delete hooks
// drupal 7.x
function indextank_node_insert($node) {
  $index = get_indextank_index();
  indextank_index_document($index, $node);
}

function indextank_node_update($node) {
  $index = get_indextank_index();
  indextank_index_document($index, $node);
}

function indextank_node_delete($node) {
  $index = get_indextank_index();
  indextank_delete_document($index, $node);
}

// drupal 6.x
function indextank_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  if ($op == 'insert' || $op == 'update') {
    $index = get_indextank_index();
    indextank_index_document($index, $node);
  } elseif ($op == 'delete') {
    $index = get_indextank_index();
    indextank_delete_document($index, $node);
  }
}


// Private functions
function get_indextank_index() {
    $api_url = variable_get('indextank_apiurl', '');
    $index_name = 'drupal';
  
    $api = new ApiClient($api_url);
    $index = $api->get_index($index_name);
    return $index;
}

function indextank_admin_validate($form, &$form_state) {
  $api_url = $form_state['values']['indextank_apiurl'];
  if (!indextank_valid_apiurl($api_url)) {
    form_set_error('indextank_apiurl', t('You must enter a valid IndexTank api url.'));
  }
}

function indextank_index_document($index, $document) {
  $data = indextank_get_fields($document);
  $docid = $document->nid;
  $index->add_document($docid, $data);
}

function indextank_delete_document($index, $document) {
  $docid = $document->nid;
  $index->delete_document($docid);
}

function indextank_get_fields($document) {
  if (is_array($document->body)) {
    $text = utf8_encode($document->body['und'][0]['value']);
  } else {
    $text = utf8_encode($document->body);
  }
  $fields = array(
    'url' => url("node/{$document->nid}"),
    'title' => utf8_encode($document->title),
    'content' => $text,
    'user' => $document->name,
    'timestamp' => $document->timestamp,
  );

  return $fields;
}

function indextank_valid_apiurl($api_url) {
  return (bool) preg_match("
      /^http:\/\/:[[:alnum:][:punct:]]+@[a-z0-9]{3,8}\.api\.indextank\.com$/",
      $api_url);
}

function is_drupal_version_6() {
  $system_info = file_get_contents(drupal_get_path('module', 'system') . '/system.info');
  $ret = (bool) preg_match("/.*6\.x.*/", $system_info);
  return $ret;
}
